services:
  - type: web
    name: sanjeri-perfume
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sanjeri_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sanjeri-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: sanjeri-db
    databaseName: sanjeri
    user: sanjeri_user
    plan: free